theme: jekyll-theme-hacker
google_analytics: UA-190454037-1
markdown: kramdown
kramdown:
    math_engine: mathjax
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

url: "https://johnwestonnull.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap